# Generated by Django 5.2 on 2025-05-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('Bath', 'Bath'), ('Haircut', 'Haircut'), ('Nail Trim', 'Nail Trim'), ('Full Grooming', 'Full Grooming')], max_length=100),
        ),
    ]
