# Generated by Django 5.2 on 2025-05-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_email_booking_full_name_booking_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='full_name',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='pet_name',
        ),
    ]
